[features]
seeds = false
skip-lint = false
[programs.localnet]
tea_vs_coffee = "FYZUbgD7cSJn4M9aB9eZtvQ6r8yau9R5A7jog4ZSeGri"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/sammanadh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait=10000
